[workspace]
members = [
    "orbit-cache",
    "orbit-event",
    "orbit-lock",
    "orbit-rs",
    "orbit-metrics",
]
resolver = "3"

[workspace.package]
edition = "2024"
authors = ["ilker Arabaci <iadeveloper@hotmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/iadev09/orbit"

[workspace.dependencies]
bytes = "1.11"
criterion = "0.8.2"
dashmap = "6.1"
libc = "0.2"
lru = "0.18"
netid64 = "0.1.1"
nix = { version = "0.31", features = ["process", "signal", "user", "fs"] }
tracing = "0.1.44"
